steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/aisa-frontend:$COMMIT_SHA'
      - '--build-arg'
      - 'VITE_GOOGLE_CLIENT_ID=743928421487-4k3rngu52s9ts2mpr032ladvu72v6ll7.apps.googleusercontent.com'
      - '.'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/aisa-frontend:$COMMIT_SHA']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'aisa-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/aisa-frontend:$COMMIT_SHA'
      - '--region'
      - 'asia-south1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/aisa-frontend:$COMMIT_SHA'
