import React, { createContext, useContext } from 'react';
import { usePersonalization } from './PersonalizationContext';

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
    const { personalizations, updatePersonalization } = usePersonalization();

    // Single Source of Truth from PersonalizationContext
    const language = personalizations?.general?.language || 'English';
    const region = personalizations?.general?.region || 'India';

    const setLanguage = (lang) => updatePersonalization('general', { language: lang });
    const setRegion = (reg) => updatePersonalization('general', { region: reg });

    const regions = {
        'India': ["English", "Hindi", "Bengali", "Marathi", "Telugu", "Tamil", "Kannada", "Malayalam", "Urdu"],
        'United States': ["English", "Spanish", "French", "Mandarin Chinese"],
        'Japan': ["Japanese", "English"],
        'China': ["Mandarin Chinese", "English"],
        'Germany': ["German", "English"],
        'France': ["French", "English"],
        'Brazil': ["Portuguese", "English"],
        'United Kingdom': ["English"],
        'United Arab Emirates': ["Arabic", "English"],
        'Canada': ["English", "French"],
        'Spain': ["Spanish", "English"],
        'South Korea': ["Korean", "English"],
        'Italy': ["Italian", "English"],
        'Russia': ["Russian", "English"],
        'Australia': ["English"],
        'Singapore': ["English", "Mandarin Chinese", "Malayalam", "Tamil"],
        'Netherlands': ["Dutch", "English"],
        'Mexico': ["Spanish", "English"],
        'Turkey': ["Turkish", "English"],
        'Switzerland': ["German", "French", "Italian", "English"],
        'Sweden': ["Swedish", "English"],
        'Norway': ["Norwegian", "English"],
        'Denmark': ["Danish", "English"],
        'Finland': ["Finnish", "English"],
        'Belgium': ["Dutch", "French", "German", "English"],
        'Argentina': ["Spanish", "English"],
        'Portugal': ["Portuguese", "English"],
        'New Zealand': ["English"],
        'South Africa': ["English", "Afrikaans", "Zulu", "Xhosa"]
    };

    const regionFlags = {
        'India': 'IN',
        'United States': 'US',
        'Japan': 'JP',
        'China': 'CN',
        'Germany': 'DE',
        'France': 'FR',
        'Brazil': 'BR',
        'United Kingdom': 'GB',
        'United Arab Emirates': 'AE',
        'Canada': 'CA',
        'Spain': 'ES',
        'South Korea': 'KR',
        'Italy': 'IT',
        'Russia': 'RU',
        'Australia': 'AU',
        'Singapore': 'SG',
        'Netherlands': 'NL',
        'Mexico': 'MX',
        'Turkey': 'TR',
        'Switzerland': 'CH',
        'Sweden': 'SE',
        'Norway': 'NO',
        'Denmark': 'DK',
        'Finland': 'FI',
        'Belgium': 'BE',
        'Argentina': 'AR',
        'Portugal': 'PT',
        'New Zealand': 'NZ',
        'South Africa': 'ZA'
    };

    const regionTimezones = {
        'India': 'India (GMT+5:30)',
        'United States': 'Eastern Time (GMT-5:00)',
        'Japan': 'Japan Standard Time (GMT+9:00)',
        'China': 'China Standard Time (GMT+8:00)',
        'Germany': 'Central European Time (GMT+1:00)',
        'France': 'Central European Time (GMT+1:00)',
        'Brazil': 'Brasília Time (GMT-3:00)',
        'United Kingdom': 'Greenwich Mean Time (GMT+0:00)',
        'United Arab Emirates': 'Gulf Standard Time (GMT+4:00)',
        'Canada': 'Eastern Time (GMT-5:00)',
        'Spain': 'Central European Time (GMT+1:00)',
        'South Korea': 'Korea Standard Time (GMT+9:00)',
        'Italy': 'Central European Time (GMT+1:00)',
        'Russia': 'Moscow Time (GMT+3:00)',
        'Australia': 'Australian Eastern Time (GMT+10:00)',
        'Singapore': 'Singapore Time (GMT+8:00)',
        'Netherlands': 'Central European Time (GMT+1:00)',
        'Mexico': 'Central Standard Time (GMT-6:00)',
        'Turkey': 'Turkey Time (GMT+3:00)',
        'Switzerland': 'Central European Time (GMT+1:00)',
        'Sweden': 'Central European Time (GMT+1:00)',
        'Norway': 'Central European Time (GMT+1:00)',
        'Denmark': 'Central European Time (GMT+1:00)',
        'Finland': 'Eastern European Time (GMT+2:00)',
        'Belgium': 'Central European Time (GMT+1:00)',
        'Argentina': 'Argentina Time (GMT-3:00)',
        'Portugal': 'Western European Time (GMT+0:00)',
        'New Zealand': 'New Zealand Time (GMT+12:00)',
        'South Africa': 'South Africa Time (GMT+2:00)'
    };

    const allTimezones = [
        "International Date Line West (GMT-12:00)",
        "Samoa Standard Time (GMT-11:00)",
        "Hawaii-Aleutian Standard Time (GMT-10:00)",
        "Alaska Standard Time (GMT-9:00)",
        "Pacific Standard Time (GMT-8:00)",
        "Mountain Standard Time (GMT-7:00)",
        "Central Standard Time (GMT-6:00)",
        "Eastern Standard Time (GMT-5:00)",
        "Atlantic Standard Time (GMT-4:00)",
        "Brasília Time (GMT-3:00)",
        "South Georgia Time (GMT-2:00)",
        "Azores Time (GMT-1:00)",
        "Greenwich Mean Time (GMT+0:00)",
        "Central European Time (GMT+1:00)",
        "Eastern European Time (GMT+2:00)",
        "Moscow Time (GMT+3:00)",
        "Gulf Standard Time (GMT+4:00)",
        "India Standard Time (GMT+5:30)",
        "Bangladesh Standard Time (GMT+6:00)",
        "Indochina Time (GMT+7:00)",
        "China Standard Time (GMT+8:00)",
        "Japan Standard Time (GMT+9:00)",
        "Australian Eastern Time (GMT+10:00)",
        "Solomon Islands Time (GMT+11:00)",
        "New Zealand Time (GMT+12:00)"
    ];

    const languages = [].concat(...Object.values(regions));
    const uniqueLanguages = [...new Set(languages)];

    const translations = {
        "English": {
            displayLanguage: "Display Language",
            dashboard: "Dashboard",
            chat: "Chat",
            billing: "Billing",
            updates: "Updates",
            helpFaq: "Help & FAQ",
            logOut: "Log Out",
            joined: "Joined December 2025",
            securityBtn: "Security & Guidelines",
            totalSessions: "Total Sessions",
            proFeatures: "Pro Features",
            accountSettings: "Account Settings",
            credits: "Credits",
            accountPreferences: "Account Preferences",
            timezone: "Timezone",
            currency: "Currency",
            theme: "Theme",
            securityStatus: "Security Status",
            accountSecure: "Account fully secure",
            twoFactor: "Two-Factor Authentication",
            enabled: "Enabled",
            manage: "Manage",
            signOut: "Sign Out from Device",
            logIn: "Log In",
            selectIssueCategory: "Select Issue Category",
            describeYourIssue: "Describe your issue",
            issuePlaceholder: "Please provide details about the problem you are facing...",
            submitSupport: "Submit Support",
            successOwned: "Successfully Owned",
            newChat: "New Chat",
            history: "History",
            aiPersonalAssistant: "AI Personal Assistant",
            manageDailyRoutine: "Manage your daily routine & smart reminders",
            newTask: "New Task",
            todayTasks: "Today's Tasks",
            pending: "Pending",
            completed: "Completed",
            totalRoutines: "Total Routines",
            all: "All",
            today: "Today",
            noTasksFound: "No tasks found",
            addFirstTask: "Add a new task to get started.",
            editTask: "Edit Task",
            title: "Title",
            description: "Description",
            date: "Date",
            time: "Time",
            category: "Category",
            repeat: "Repeat",
            noRepeat: "No Repeat",
            daily: "Daily",
            weekly: "Weekly",
            monthly: "Monthly",
            yearly: "Yearly",
            urgentMode: "Urgent Mode (Persistent Alarm)",
            saveTask: "Save Task",
            Personal: "Personal",
            Work: "Work",
            Office: "Office",
            Meeting: "Meeting",
            Health: "Health",
            Education: "Education",
            Finance: "Finance",
            Shopping: "Shopping",
            Traveling: "Traveling",
            welcomeMessage: "Hello! I’m AISA, your Artificial Intelligence Super Assistant. How can I help you today?",
            switchedTo: "Switched to",
            heroTitle: "The Future of Conversational AI",
            heroSubtitle: "Experience the next generation of intelligent assistance. AISA ™ learns, adapts, and creates with you in real-time through a stunning interface.",
            startNow: "Start Now",
            privacyTitle: "Privacy First",
            privacyDesc: "Your data is yours. End-to-end encryption for all conversations.",
            intelligenceTitle: "Next-Gen Intelligence",
            intelligenceDesc: "Powered by the most advanced neural networks for human-like reasoning.",
            interactionTitle: "Natural Interaction",
            interactionDesc: "Voice, text, or files—interact in the way that feels most natural.",
            support: "Support",
            contact: "Contact",
            city: "Jabalpur, Madhya Pradesh",
            allRightsReserved: "All rights reserved.",
            privacyPolicy: "Privacy Policy",
            termsOfService: "Terms of Service",
            cookiePolicy: "Cookie Policy",
            helpCenter: "Help Center",
            aboutAisa: "About AISA",
            apiConnectionError: "Sorry, I am having trouble connecting to the AISA network right now. Please check your connection.",
            apiQuotaExceeded: "The AISA system is currently busy (Quota limit reached). Please wait 60 seconds and try again.",
            faq: "FAQ",
            help: "Help",
            existingUser: "Existing User",
            sendToSupport: "Send to Support",
            ticketSuccess: "Ticket Submitted Successfully! Our team will contact you soon.",
            ticketError: "Failed to submit ticket. Please try again or email us directly.",
            orEmailUs: "Or email us directly at",
            faqSubtext: "Get quick answers to common questions about our platform",
            close: "Close",
            dbDemoModeMessage: "I'm having trouble connecting to my memory, but I can still chat! (Demo Mode)",
            // Profile Settings
            settings: "Settings",
            general: "General",
            notifications: "Notifications",
            personalization: "Personalization",
            dataControls: "Data controls",
            security: "Security",
            account: "Account",
            logOut: "Log out",
            appearance: "Appearance",
            appearanceDesc: "Choose your preferred layout theme.",
            fontSize: "Font Size",
            fontSizeDesc: "Adjust text size for better readability.",
            accentColor: "Accent color",
            accentColorDesc: "Personalize your AI's identity color.",
            language: "Language",
            languageDesc: "Select your preferred dashboard language.",
            inbox: "Inbox",
            clearAll: "Clear all",
            addSwitchAccount: "Add or switch account",
            resetAllSettings: "Reset all settings to defaults",
            deleteAccount: "Permanent Delete Account",
            lastUpdated: "Last Updated",
            privacyPolicy: "Privacy Policy",
            termsOfService: "Terms of Service",
            cookiePolicy: "Cookie Policy"
        },
        "Hindi": {
            displayLanguage: "प्रदर्शित भाषा",
            dashboard: "डैशबोर्ड",
            chat: "चैट",
            myAgents: "मेरे एजेंट्स",
            marketplace: "मार्केटप्लेस",
            vendorDashboard: "विक्रेता डैशबोर्ड",
            billing: "बिलिंग",
            adminDashboard: "एडमिन डैशबोर्ड",
            updates: "अपडेट",
            helpFaq: "सहायता और FAQ",
            logOut: "लॉग आउट",
            joined: "दिसंबर 2025 को शामिल हुए",
            securityBtn: "सुरक्षा और दिशानिर्देश",
            totalSessions: "कुल सत्र",
            proFeatures: "प्रो सुविधाएँ",
            accountSettings: "खाता सेटिंग्स",
            credits: "क्रेडिट",
            accountPreferences: "खाता प्राथमिकताएं",
            timezone: "समय क्षेत्र",
            currency: "मुद्रा",
            theme: "थीम",
            securityStatus: "सुरक्षा स्थिति",
            accountSecure: "खाता पूरी तरह से सुरक्षित है",
            twoFactor: "दो-चरणीय प्रमाणीकरण",
            enabled: "सक्षम",
            manage: "प्रबंधित करें",
            signOut: "साइन आउट",
            logIn: "लॉग इन",
            selectIssueCategory: "समस्या श्रेणी चुनें",
            describeYourIssue: "अपनी समस्या का वर्णन करें",
            issuePlaceholder: "कृपया उस समस्या के बारे में विवरण प्रदान करें जिसका आप सामना कर रहे हैं...",
            submitSupport: "सपोर्ट जमा करें",
            successOwned: "सफलतापूर्वक स्वामित्व में",
            newChat: "नई चैट",
            history: "इतिहास",
            aiPersonalAssistant: "एआई पर्सनल असिस्टेंट",
            manageDailyRoutine: "अपनी दैनिक दिनचर्या और स्मार्ट रिमाइंडर प्रबंधित करें",
            newTask: "नया कार्य",
            todayTasks: "आज के कार्य",
            pending: "लंबित",
            completed: "पूरा हुआ",
            totalRoutines: "कुल दिनचर्या",
            all: "सभी",
            today: "आज",
            noTasksFound: "कोई कार्य नहीं मिला",
            addFirstTask: "शुरू करने के लिए एक नया कार्य जोड़ें.",
            editTask: "कार्य संपादित करें",
            title: "शीर्षक",
            description: "विवरण",
            date: "तारीख",
            time: "समय",
            category: "श्रेणी",
            repeat: "दोहराएं",
            noRepeat: "दोहराएं नहीं",
            daily: "दैनिक",
            weekly: "साप्ताहिक",
            monthly: "मासिक",
            yearly: "वार्षिक",
            urgentMode: "अर्जेंट मोड (लगातार अलार्म)",
            saveTask: "कार्य सहेजें",
            Personal: "व्यक्तिगत",
            Work: "कार्य",
            Office: "कार्यालय",
            Meeting: "बैठक",
            Health: "स्वास्थ्य",
            Education: "शिक्षा",
            Finance: "वित्त",
            Shopping: "खरीदारी",
            Traveling: "यात्रा",
            switchedTo: "पर स्विच किया गया",
            heroTitle: "संवादात्मक एआई का भविष्य",
            heroSubtitle: "इंटेलिजेंट सहायता की अगली पीढ़ी का अनुभव करें। AISA ™ एक शानदार इंटरफ़ेस के माध्यम से वास्तविक समय में आपके साथ सीखता है, अनुकूलित होता है और बनाता है।",
            startNow: "अभी शुरू करें",
            privacyTitle: "गोपनीयता पहले",
            privacyDesc: "आपका डेटा आपका है। सभी बातचीत के लिए एंड-टू-एंड एन्क्रिप्शन।",
            intelligenceTitle: "अगली पीढ़ी की बुद्धिमत्ता",
            intelligenceDesc: "मानव जैसी तर्कशक्ति के लिए सबसे उन्नत तंत्रिका नेटवर्क द्वारा संचालित।",
            interactionTitle: "प्राकृतिक संपर्क",
            interactionDesc: "आवाज, पाठ या फाइलें—उस तरह से बातचीत करें जो सबसे प्राकृतिक लगे।",
            support: "सहायता",
            contact: "संपर्क",
            city: "जबलपुर, मध्य प्रदेश",
            allRightsReserved: "सर्वाधिकार सुरक्षित।",
            privacyPolicy: "गोपनीयता नीति",
            termsOfService: "सेवा की शर्तें",
            cookiePolicy: "कुकी नीति",
            helpCenter: "सहायता केंद्र",
            aboutAisa: "AISA के बारे में",
            apiConnectionError: "क्षमा करें, मुझे अभी AISA नेटवर्क से जुड़ने में समस्या हो रही है। कृपया अपना कनेक्शन जांचें।",
            apiQuotaExceeded: "AISA सिस्टम अभी व्यस्त है (कोटा सीमा पूरी हो गई)। कृपया 60 सेकंड प्रतीक्षा करें और पुनः प्रयास करें।",
            welcomeMessage: "नमस्ते! मैं AISA हूं, आपकी आर्टिफिशियल इंटेलिजेंस सुपर असिस्टेंट। मैं आज आपकी कैसे मदद कर सकता हूँ?",
            faq: "सामान्य प्रश्न",
            help: "सहायता",
            existingUser: "मौजूदा उपयोगकर्ता",
            sendToSupport: "समर्थन को भेजें",
            ticketSuccess: "टिकट सफलतापूर्वक जमा किया गया! हमारी टीम जल्द ही आपसे संपर्क करेगी।",
            ticketError: "टिकट जमा करने में विफल। कृपया पुन: प्रयास करें या हमें सीधे ईमेल करें।",
            orEmailUs: "या हमें सीधे ईमेल करें",
            faqSubtext: "हमारे प्लेटफॉर्म के बारे में सामान्य प्रश्नों के त्वरित उत्तर प्राप्त करें",
            close: "बंद करें",
            dbDemoModeMessage: "मुझे अपनी याददाश्त (डेटाबेस) से जुड़ने में समस्या हो रही है, लेकिन मैं अभी भी बातचीत कर सकता हूँ! (डेमो मोड)",
            // Profile Settings
            settings: "सेटिंग्स",
            general: "सामान्य",
            notifications: "सूचनाएं",
            personalization: "व्यक्तिगतकरण",
            dataControls: "डेटा नियंत्रण",
            security: "सुरक्षा",
            account: "खाता",
            logOut: "लॉग आउट",
            appearance: "दिखावट",
            appearanceDesc: "अपनी पसंदीदा लेआउट थीम चुनें।",
            fontSize: "फॉन्ट साइज़",
            fontSizeDesc: "बेहतर पठनीयता के लिए टेक्स्ट साइज़ समायोजित करें।",
            accentColor: "एक्सेंट कलर",
            accentColorDesc: "अपने AI के पहचान रंग को व्यक्तिगत बनाएं।",
            language: "भाषा",
            languageDesc: "अपनी पसंदीदा डैशबोर्ड भाषा चुनें।",
            inbox: "इनबॉक्स",
            clearAll: "सभी साफ़ करें",
            addSwitchAccount: "खाता जोड़ें या बदलें",
            resetAllSettings: "सभी सेटिंग्स को डिफॉल्ट पर रीसेट करें",
            deleteAccount: "खाता स्थायी रूप से हटाएं",
            lastUpdated: "अंतिम अपडेट",
            privacyPolicy: "गोपनीयता नीति",
            termsOfService: "सेवा की शर्तें",
            cookiePolicy: "कुकी नीति"
        },
        "Spanish": {
            displayLanguage: "Idioma de pantalla",
            dashboard: "Tablero",
            chat: "Chat",
            billing: "Facturación",
            updates: "Actualizaciones",
            helpFaq: "Ayuda y FAQ",
            logOut: "Cerrar sesión",
            joined: "Se unió en diciembre de 2025",
            securityBtn: "Seguridad y directrices",
            totalSessions: "Sesiones totales",
            proFeatures: "Funciones Pro",
            accountSettings: "Configuración de la cuenta",
            credits: "Créditos",
            accountPreferences: "Preferencias de la cuenta",
            timezone: "Zona horaria",
            currency: "Moneda",
            theme: "Tema",
            securityStatus: "Estado de seguridad",
            accountSecure: "Cuenta totalmente segura",
            twoFactor: "Autenticación de dos factores",
            enabled: "Habilitado",
            manage: "Administrar",
            signOut: "Cerrar sesión",
            heroTitle: "El Futuro de la IA Conversacional",
            heroSubtitle: "Experimente la próxima generación de asistencia inteligente. AISA ™ aprende, se adapta y crea con usted en tiempo real a través de una interfaz impresionante.",
            startNow: "Empezar Ahora",
            privacyTitle: "Privacidad Primero",
            privacyDesc: "Sus datos son suyos. Cifrado de extremo a extremo para todas las conversaciones.",
            intelligenceTitle: "Inteligencia de Próxima Generación",
            intelligenceDesc: "Impulsado por las redes neuronales más avanzadas para un razonamiento similar al humano.",
            interactionTitle: "Interacción Natural",
            interactionDesc: "Voz, texto o archivos: interactúe de la manera que le resulte más natural.",
            support: "Soporte",
            contact: "Contacto",
            city: "Jabalpur, Madhya Pradesh",
            allRightsReserved: "Todos los derechos reservados.",
            privacyPolicy: "Política de Privacidad",
            termsOfService: "Términos de Servicio",
            cookiePolicy: "Política de Cookies",
            helpCenter: "Centro de Ayuda",
            aboutAisa: "Acerca de AISA",
            apiConnectionError: "Lo siento, tengo problemas para conectarme a la red AISA en este momento. Por favor, comprueba tu conexión.",
            apiQuotaExceeded: "El sistema AISA está ocupado actualmente (Límite de cuota alcanzado). Por favor, espere 60 segundos e inténtelo de nuevo.",
            welcomeMessage: "¡Hola! Soy AISA, tu Super Asistente de Inteligencia Artificial. ¿Cómo puedo ayudarte hoy?",
            faq: "Preguntas Frecuentes",
            help: "Ayuda",
            existingUser: "Usuario Existente",
            sendToSupport: "Enviar a Soporte",
            ticketSuccess: "¡Ticket enviado con éxito! Nuestro equipo se pondrá en contacto pronto.",
            ticketError: "Error al enviar el ticket. Por favor, inténtelo de nuevo o envíenos un correo.",
            orEmailUs: "O envíenos un correo directamente a",
            faqSubtext: "Obtenga respuestas rápidas a preguntas comunes sobre nuestra plataforma",
            close: "Cerrar",
            dbDemoModeMessage: "Tengo problemas para conectarme a mi memoria, ¡pero aún puedo chatear! (Modo Demo)"
        },
        "French": {
            displayLanguage: "Langue d'affichage",
            dashboard: "Tableau de bord",
            chat: "Chat",
            billing: "Facturation",
            updates: "Mises à jour",
            helpFaq: "Aide & FAQ",
            logOut: "Déconnexion",
            joined: "Inscrit en décembre 2025",
            securityBtn: "Sécurité & Directives",
            totalSessions: "Total des sessions",
            proFeatures: "Fonctions Pro",
            accountSettings: "Paramètres du compte",
            credits: "Crédits",
            accountPreferences: "Préférences du compte",
            timezone: "Fuseau horaires",
            currency: "Devise",
            theme: "Thème",
            securityStatus: "État de sécurité",
            accountSecure: "Compte entièrement sécurisé",
            twoFactor: "Authentification à deux facteurs",
            enabled: "Activé",
            manage: "Gérer",
            signOut: "Déconnexion",
            heroTitle: "L'Avenir de l'IA Conversationnelle",
            heroSubtitle: "Découvrez la prochaine génération d'assistance intelligente. AISA ™ apprend, s'adapte et crée avec vous en temps réel grâce à une interface époustouflante.",
            startNow: "Démarrer Maintenant",
            privacyTitle: "La Confidentialité d'abord",
            privacyDesc: "Vos données vous appartiennent. Cryptage de bout en bout pour toutes les conversations.",
            intelligenceTitle: "Intelligence de Nouvelle Génération",
            intelligenceDesc: "Propulsé par les réseaux neuronaux les plus avancés pour un raisonnement humain.",
            interactionTitle: "Interaction Naturelle",
            interactionDesc: "Voix, texte ou fichiers : interagissez de la manière la plus naturelle pour vous.",
            support: "Support",
            contact: "Contact",
            city: "Jabalpur, Madhya Pradesh",
            allRightsReserved: "Tous droits réservés.",
            privacyPolicy: "Politique de Confidentialité",
            termsOfService: "Conditions d'Utilisation",
            cookiePolicy: "Politique Relative aux Cookies",
            helpCenter: "Centre d'Aide",
            aboutAisa: "À propos d'AISA",
            apiConnectionError: "Désolé, j'ai du mal à me connecter au réseau AISA pour le moment. Veuillez vérifier votre connexion.",
            apiQuotaExceeded: "Le système AISA est actuellement occupé (limite de quota atteinte). Veuillez patienter 60 secondes et réessayer.",
            welcomeMessage: "Bonjour! Je suis AISA, votre super assistant d'intelligence artificielle. Comment puis-je vous aider aujourd'hui?",
            faq: "FAQ",
            help: "Aide",
            existingUser: "Utilisateur Existant",
            sendToSupport: "Envoyer au Support",
            ticketSuccess: "Billet soumis avec succès ! Notre équipe vous contactera bientôt.",
            ticketError: "Échec de l'envoi du billet. Veuillez réessayer ou nous envoyer un e-mail directement.",
            orEmailUs: "Ou envoyez-nous un e-mail directement à",
            faqSubtext: "Obtenez des réponses rapides aux questions courantes sur notre plateforme",
            close: "Fermer",
            dbDemoModeMessage: "J'ai du mal à me connecter à ma mémoire, mais je peux toujours discuter ! (Mode Démo)"
        },
        "Japanese": {
            displayLanguage: "表示言語",
            dashboard: "ダッシュボード",
            chat: "チャット",
            myAgents: "マイエージェント",
            marketplace: "マーケットプレイス",
            vendorDashboard: "ベンダーダッシュボード",
            billing: "請求",
            adminDashboard: "管理ダッシュボード",
            updates: "アップデート",
            helpFaq: "ヘルプとFAQ",
            logOut: "ログアウト",
            joined: "2025年12月に参加",
            securityBtn: "セキュリティとガイドライン",
            totalSessions: "総セッション数",
            proFeatures: "プロ機能",
            accountSettings: "アカウント設定",
            credits: "クレジット",
            accountPreferences: "アカウント設定",
            timezone: "タイムゾーン",
            currency: "通貨",
            theme: "テーマ",
            securityStatus: "セキュリティステータス",
            accountSecure: "アカウントは完全に安全です",
            twoFactor: "2要素認証",
            enabled: "有効",
            manage: "管理",
            signOut: "ログアウト",
            switchedTo: "に切り替えました",
            heroTitle: "対話型AIの未来",
            heroSubtitle: "次世代のインテリジェントサポートを体験してください。AISA ™ は、素晴らしいインターフェースを通じて、リアルタイムであなたと共に学び、適応し、創造します。",
            startNow: "今すぐ開始",
            privacyTitle: "プライバシー第一",
            privacyDesc: "あなたのデータはあなたのものです。すべての会話に対してエンドツーエンドの暗号化を適用します。",
            intelligenceTitle: "次世代のインテリジェンス",
            intelligenceDesc: "人間のような推論を実現するために、最も高度なニューラルネットワークを搭載しています。",
            interactionTitle: "自然なインタラクション",
            interactionDesc: "音声、テキスト、またはファイル - あなたにとって最も自然に感じる方法で対話してください。",
            support: "サポート",
            contact: "お問い合わせ",
            city: "ジャバルプル、マディヤ・プラデーシュ州",
            allRightsReserved: "全著作権所有。",
            privacyPolicy: "プライバシーポリシー",
            termsOfService: "利用規約",
            cookiePolicy: "クッキーポリシー",
            helpCenter: "ヘルプセンター",
            aboutAisa: "AISAについて",
            apiConnectionError: "申し訳ありませんが、现在AISAネットワークへの接続に问题が発生しています。接続を確認してください。",
            apiQuotaExceeded: "AISAシステムは現在混雑しています（クォータ制限に達しました）。 60秒待ってからもう一度お試しください。",
            welcomeMessage: "こんにちは！ 私はあなたの人工知能スーパーアシスタント、AISAです。 今日はどのようにお手伝いしましょうか？",
            faq: "よくある質問",
            help: "ヘルプ",
            existingUser: "既存ユーザー",
            sendToSupport: "サポートに送信",
            ticketSuccess: "チケットが正常に送信されました。 間もなくチームからご連絡いたします。",
            ticketError: "チケットの送信に失敗しました。 もう一度試すか、直接メールでお問い合わせください。",
            orEmailUs: "または、直接メールでお問い合わせください",
            faqSubtext: "プラットフォームに関する一般的な質問への回答を得る",
            close: "閉じる"
        },
        "German": {
            displayLanguage: "Anzeigesprache",
            dashboard: "Dashboard",
            chat: "Chat",
            myAgents: "Meine Agenten",
            marketplace: "Marktplatz",
            vendorDashboard: "Verkäufer-Dashboard",
            billing: "Abrechnung",
            adminDashboard: "Admin-Dashboard",
            updates: "Updates",
            helpFaq: "Hilfe & FAQ",
            logOut: "Abmelden",
            joined: "Beigetreten im Dezember 2025",
            securityBtn: "Sicherheit & Richtlinien",
            totalSessions: "Gesamte Sitzungen",
            proFeatures: "Pro-Funktionen",
            accountSettings: "Kontoeinstellungen",
            credits: "Credits",
            accountPreferences: "Kontoeinstellungen",
            timezone: "Zeitzone",
            currency: "Währung",
            theme: "Thema",
            securityStatus: "Sicherheitsstatus",
            accountSecure: "Konto vollständig sicher",
            twoFactor: "Zwei-Faktor-Authentifizierung",
            enabled: "Aktiviert",
            manage: "Verwalten",
            signOut: "Abmelden",
            welcomeMessage: "Hallo! Ich bin AISA, Ihr Künstlicher Intelligenz Super Assistent. Wie kann ich Ihnen heute helfen?",
            switchedTo: "Umgeschaltet auf",
            heroTitle: "Die Zukunft der konversationsbasierten KI",
            heroSubtitle: "Erleben Sie die nächste Generation intelligenter Unterstützung. AISA ™ lernt, passt sich an und erstellt mit Ihnen in Echtzeit über eine beeindruckende Benutzeroberfläche.",
            startNow: "Jetzt starten",
            privacyTitle: "Datenschutz geht vor",
            privacyDesc: "Ihre Daten gehören Ihnen. End-to-end Verschlüsselung für alle Gespräche.",
            intelligenceTitle: "Intelligenz der nächsten Generation",
            intelligenceDesc: "Unterstützt durch die fortschrittlichsten neuronalen Netzwerke für menschenähnliches Denken.",
            interactionTitle: "Natürliche Interaktion",
            interactionDesc: "Sprache, Text oder Dateien – interagieren Sie so, wie es sich am natürlichsten anfühlt.",
            support: "Unterstützung",
            contact: "Kontakt",
            city: "Jabalpur, Madhya Pradesh",
            allRightsReserved: "Alle Rechte vorbehalten.",
            privacyPolicy: "Datenschutzerklärung",
            termsOfService: "Nutzungsbedingungen",
            cookiePolicy: "Cookie-Richtlinie",
            helpCenter: "Hilfe-Center",
            aboutAisa: "Über AISA",
            apiConnectionError: "Entschuldigung, ich habe momentan Probleme, mich mit dem AISA-Netzwerk zu verbinden. Bitte überprüfen Sie Ihre Verbindung.",
            apiQuotaExceeded: "Das AISA-System ist derzeit ausgelastet (Kontingentlimit erreicht). Bitte warten Sie 60 Sekunden und versuchen Sie es erneut.",
            faq: "FAQ",
            help: "Hilfe",
            existingUser: "Bestehender Benutzer",
            sendToSupport: "An Support senden",
            ticketSuccess: "Ticket erfolgreich eingereicht! Unser Team wird Sie bald kontaktieren.",
            ticketError: "Fehler beim Einreichen des Tickets. Bitte versuchen Sie es erneut oder senden Sie uns direkt eine E-Mail.",
            orEmailUs: "Oder senden Sie uns direkt eine E-Mail an",
            faqSubtext: "Erhalten Sie schnelle Antworten auf häufig gestellte Fragen zu unserer Plattform",
            close: "Schließen"
        },
        "Portuguese": {
            displayLanguage: "Idioma de exibição",
            dashboard: "Painel",
            chat: "Chat",
            myAgents: "Meus Agentes",
            marketplace: "Mercado",
            vendorDashboard: "Painel do Vendedor",
            billing: "Faturamento",
            adminDashboard: "Painel do Administrador",
            updates: "Atualizações",
            helpFaq: "Ajuda e FAQ",
            logOut: "Sair",
            joined: "Entrou em dezembro de 2025",
            securityBtn: "Segurança e Diretrizes",
            totalSessions: "Total de Sessões",
            proFeatures: "Recursos Pro",
            accountSettings: "Configurações da Conta",
            credits: "Créditos",
            accountPreferences: "Preferências da Conta",
            timezone: "Fuso Horário",
            currency: "Moeda",
            theme: "Tema",
            securityStatus: "Status de Segurança",
            accountSecure: "Conta totalmente segura",
            twoFactor: "Autenticação de Dois Fatores",
            enabled: "Ativado",
            manage: "Gerenciar",
            signOut: "Sair",
            welcomeMessage: "Olá! Eu sou o AISA, seu Super Assistente de Inteligência Artificial. Como posso ajudar você hoje?",
            switchedTo: "Alterado para",
            heroTitle: "O Futuro da IA Conversacional",
            heroSubtitle: "Experimente a próxima geração de suporte inteligente. O AISA ™ aprende, adapta-se e cria com você em tempo real através de uma interface impressionante.",
            startNow: "Começar Agora",
            privacyTitle: "Privacidade em Primeiro Lugar",
            privacyDesc: "Seus dados pertencem a você. Criptografia de ponta a ponta para todas as conversas.",
            intelligenceTitle: "Inteligência de Próxima Geração",
            intelligenceDesc: "Alimentado pelas redes neurais mais avançadas para raciocínio semelhante ao humano.",
            interactionTitle: "Interação Natural",
            interactionDesc: "Voz, texto ou arquivos – interaja da forma que parecer mais natural.",
            support: "Suporte",
            contact: "Contato",
            city: "Jabalpur, Madhya Pradesh",
            allRightsReserved: "Todos os direitos reservados.",
            privacyPolicy: "Política de Privacidade",
            termsOfService: "Termos de Serviço",
            cookiePolicy: "Política de Cookies",
            helpCenter: "Central de Ajuda",
            aboutAisa: "Sobre o AISA",
            apiConnectionError: "Desculpe, estou com problemas para me conectar à rede AISA no momento. Verifique sua conexão.",
            apiQuotaExceeded: "O sistema AISA está ocupado no momento (limite de cota atingido). Aguarde 60 segundos e tente novamente.",
            faq: "FAQ",
            help: "Ajuda",
            existingUser: "Usuário Existente",
            sendToSupport: "Enviar para o Suporte",
            ticketSuccess: "Ticket enviado com sucesso! Nossa equipe entrará em contato em breve.",
            ticketError: "Falha ao enviar o ticket. Tente novamente ou envie um e-mail diretamente.",
            orEmailUs: "Ou envie um e-mail diretamente para",
            faqSubtext: "Obtenha respostas rápidas para perguntas comuns sobre nossa plataforma",
            close: "Fechar"
        },
        "Korean": {
            displayLanguage: "표시 언어",
            dashboard: "대시보드",
            chat: "채팅",
            myAgents: "내 에이전트",
            marketplace: "마켓플레이스",
            vendorDashboard: "판매자 대시보드",
            billing: "결제",
            adminDashboard: "관리자 대시보드",
            updates: "업데이트",
            helpFaq: "도움말 및 FAQ",
            logOut: "로그아웃",
            joined: "2025년 12월 가입",
            securityBtn: "보안 및 지침",
            totalSessions: "총 세션",
            proFeatures: "프로 기능",
            accountSettings: "계정 설정",
            credits: "크레딧",
            accountPreferences: "계정 기본 설정",
            timezone: "시간대",
            currency: "통화",
            theme: "테마",
            securityStatus: "보안 상태",
            accountSecure: "계정이 완전히 안전합니다",
            twoFactor: "2단계 인증",
            enabled: "활성화됨",
            manage: "관리",
            signOut: "로그아웃",
            welcomeMessage: "안녕하세요! 저는 당신의 인공지능 슈퍼 어시스턴트 AISA입니다. 오늘 무엇을 도와드릴까요?",
            switchedTo: "전환됨:",
            heroTitle: "대화형 AI의 미래",
            heroSubtitle: "차세대 지능형 지원을 경험해 보세요. AISA™는 멋진 인터페이스를 통해 실시간으로 사용자와 함께 배우고, 적응하며, 창조합니다.",
            startNow: "지금 시작하기",
            privacyTitle: "개인정보 보호 우선",
            privacyDesc: "귀하의 데이터는 귀하의 것입니다. 모든 대화에 대한 엔드투엔드 암호화.",
            intelligenceTitle: "차세대 지능",
            intelligenceDesc: "인간과 유사한 추론을 위한 가장 진보된 신경망으로 구동됩니다.",
            interactionTitle: "자연스러운 상호작용",
            interactionDesc: "음성, 텍스트 또는 파일 - 가장 자연스럽게 느껴지는 방식으로 상호작용하세요.",
            support: "지원",
            contact: "연락처",
            city: "Jabalpur, Madhya Pradesh",
            allRightsReserved: "모든 권리 보유.",
            privacyPolicy: "개인정보 처리방침",
            termsOfService: "서비스 약관",
            cookiePolicy: "쿠키 정책",
            helpCenter: "고객 센터",
            aboutAisa: "AISA 소개",
            apiConnectionError: "죄송합니다. 현재 AISA 네트워크에 연결하는 데 문제가 있습니다. 연결을 확인해 주세요.",
            apiQuotaExceeded: "AISA 시스템이 현재 사용량이 많습니다(할당량 초과). 60초 후에 다시 시도해 주세요.",
            faq: "자주 묻는 질문",
            help: "도움말",
            existingUser: "기존 사용자",
            sendToSupport: "지원팀에 보내기",
            ticketSuccess: "티켓이 성공적으로 제출되었습니다! 저희 팀에서 곧 연락드리겠습니다.",
            ticketError: "티켓 제출에 실패했습니다. 다시 시도하거나 직접 이메일을 보내주세요.",
            orEmailUs: "또는 다음 주소로 직접 이메일을 보내주세요:",
            faqSubtext: "플랫폼에 대한 일반적인 질문에 대한 빠른 답변을 확인하세요.",
            close: "닫기"
        },
        "Russian": {
            displayLanguage: "Язык интерфейса",
            dashboard: "Панель управления",
            chat: "Чат",
            myAgents: "Мои агенты",
            marketplace: "Маркетплейс",
            vendorDashboard: "Панель продавца",
            billing: "Оплата",
            adminDashboard: "Панель админа",
            updates: "Обновления",
            helpFaq: "Помощь и FAQ",
            logOut: "Выйти",
            joined: "Присоединился в декабре 2025",
            securityBtn: "Безопасность и правила",
            totalSessions: "Всего сессий",
            proFeatures: "Pro функции",
            accountSettings: "Настройки аккаунта",
            credits: "Кредиты",
            accountPreferences: "Настройки аккаунта",
            timezone: "Часовой пояс",
            currency: "Валюта",
            theme: "Тема",
            securityStatus: "Статус безопасности",
            accountSecure: "Аккаунт полностью защищен",
            twoFactor: "Двухфакторная аутентификация",
            enabled: "Включена",
            manage: "Управлять",
            signOut: "Выйти",
            welcomeMessage: "Привет! Я AISA, ваш супер-помощник с искусственным интеллектом. Чем я могу помочь вам сегодня?",
            switchedTo: "Переключено на",
            heroTitle: "Будущее разговорного ИИ",
            heroSubtitle: "Испытайте следующее поколение интеллектуальной поддержки. AISA ™ учится, адаптируется и творит вместе с вами в режиме реального времени через потрясающий интерфейс.",
            startNow: "Начать сейчас",
            privacyTitle: "Конфиденциальность прежде всего",
            privacyDesc: "Ваши данные принадлежат вам. Свозное шифрование для всех разговоров.",
            intelligenceTitle: "Интеллект нового поколения",
            intelligenceDesc: "Работает на самых продвинутых нейронных сетях для человекоподобного мышления.",
            interactionTitle: "Естественное взаимодействие",
            interactionDesc: "Голос, текст или файлы — взаимодействуйте так, как вам удобнее всего.",
            support: "Поддержка",
            contact: "Контакт",
            city: "Джабалпур, Мадхья-Прадеш",
            allRightsReserved: "Все права защищены.",
            privacyPolicy: "Политика конфиденциальности",
            termsOfService: "Условия использования",
            cookiePolicy: "Политика использования файлов cookie",
            helpCenter: "Центр помощи",
            aboutAisa: "Об AISA",
            apiConnectionError: "Извините, сейчас у меня проблемы с подключением к сети AISA. Пожалуйста, проверьте ваше соединение.",
            apiQuotaExceeded: "Система AISA в данный момент перегружена (достигнут лимит квот). Пожалуйста, подождите 60 секунд и попробуйте снова.",
            faq: "Часто задаваемые вопросы",
            help: "Помощь",
            existingUser: "Существующий пользователь",
            sendToSupport: "Отправить в поддержку",
            ticketSuccess: "Тикет успешно отправлен! Наша команда скоро свяжется с вами.",
            ticketError: "Ошибка при отправке тикета. Пожалуйста, попробуйте еще раз или напишите нам напрямую.",
            orEmailUs: "Или напишите нам напрямую по адресу",
            faqSubtext: "Получите быстрые ответы на общие вопросы о нашей платформе",
            close: "Закрыть"
        },
        "Arabic": {
            displayLanguage: "لغة العرض",
            dashboard: "لوحة القيادة",
            chat: "دردشة",
            myAgents: "عملائي",
            marketplace: "المتجر",
            vendorDashboard: "لوحة البائع",
            billing: "الفواتير",
            adminDashboard: "لوحة المسؤول",
            updates: "التحديثات",
            helpFaq: "المساعدة والأسئلة الشائعة",
            logOut: "تسجيل الخروج",
            joined: "انضم في ديسمبر 2025",
            securityBtn: "الأمان والإرشادات",
            totalSessions: "إجمالي الجلسات",
            proFeatures: "ميزات برو",
            accountSettings: "إعدادات الحساب",
            credits: "الرصيد",
            accountPreferences: "تفضيلات الحساب",
            timezone: "المنطقة الزمنية",
            currency: "العملة",
            theme: "المظهر",
            securityStatus: "حالة الأمان",
            accountSecure: "الحساب آمن تمامًا",
            twoFactor: "المصادقة الثنائية",
            enabled: "ممكن",
            manage: "إدارة",
            signOut: "تسجيل الخروج",
            welcomeMessage: "مرحبًا! أنا AISA، مساعدك الخارق للذكاء الاصطناعي. كيف يمكنني مساعدتك اليوم؟",
            switchedTo: "تم التبديل إلى",
            heroTitle: "مستقبل الذكاء الاصطناعي التفاعلي",
            heroSubtitle: "جرب الجيل القادم من الدعم الذكي. يتعلم AISA ™ ويتكيف وينشئ معك في الوقت الفعلي من خلال واجهة مذهلة.",
            startNow: "ابدأ الآن",
            privacyTitle: "الخصوصية أولاً",
            privacyDesc: "بياناتك ملك لك. تشفير طرف إلى طرف لجميع المحادثات.",
            intelligenceTitle: "ذكاء الجيل القادم",
            intelligenceDesc: "مدعوم بأكثر الشبكات العصبية تقدمًا للتفكير الشبيه بالبشر.",
            interactionTitle: "تفاعل طبيعي",
            interactionDesc: "صوت أو نص أو ملفات - تفاعل بالطريقة التي تشعر بها بأنها طبيعية أكثر.",
            support: "الدعم",
            contact: "اتصال",
            city: "جبالبور، ماديا براديش",
            allRightsReserved: "جميع الحقوق محفوظة.",
            privacyPolicy: "سياسة الخصوصية",
            termsOfService: "شروط الخدمة",
            cookiePolicy: "سياسة ملفات الارتباط",
            helpCenter: "مركز المساعدة",
            aboutAisa: "حول AISA",
            apiConnectionError: "عذرًا، واجهت مشكلة في الاتصال بشبكة AISA الآن. يرجى التحقق من اتصالك.",
            apiQuotaExceeded: "نظام AISA مشغول حاليًا (تم الوصول إلى حد الحصة). يرجى الانتظار 60 ثانية والمحاولة مرة أخرى.",
            faq: "الأسئلة الشائعة",
            help: "مساعدة",
            existingUser: "مستخدم حالي",
            sendToSupport: "إرسال إلى الدعم",
            ticketSuccess: "تم تقديم التذكرة بنجاح! سيتصل بك فريقنا قريبًا.",
            ticketError: "فشل تقديم التذكرة. يرجى المحاولة مرة أخرى أو مراسلتنا عبر البريد الإلكتروني مباشرة.",
            orEmailUs: "أو راسلنا مباشرة على",
            faqSubtext: "احصل على إجابات سريعة للأسئلة الشائعة حول منصتنا",
            close: "إغلاق"
        },
        "Bengali": {
            displayLanguage: "প্রদর্শন ভাষা",
            dashboard: "ড্যাশবোর্ড",
            chat: "চ্যাট",
            myAgents: "আমার এজেন্ট",
            marketplace: "মার্কেটপ্লেস",
            vendorDashboard: "ভেন্ডর ড্যাশবোর্ড",
            billing: "বিলিং",
            adminDashboard: "অ্যাডমিন ড্যাশবোর্ড",
            updates: "আপডেট",
            helpFaq: "সহায়তা এবং FAQ",
            logOut: "লগ আউট",
            joined: "ডিসেম্বর 2025 এ যোগদান করেছেন",
            securityBtn: "নিরাপত্তা এবং নির্দেশিকা",
            totalSessions: "মোট সেশন",
            proFeatures: "প্রো বৈশিষ্ট্য",
            accountSettings: "অ্যাকাউন্ট সেটিংস",
            credits: "ক্রেডিট",
            accountPreferences: "অ্যাকাউন্ট পছন্দ",
            timezone: "সময় অঞ্চল",
            currency: "মুদ্রা",
            theme: "থিম",
            securityStatus: "নিরাপত্তা অবস্থা",
            accountSecure: "অ্যাকাউন্ট সম্পূর্ণ নিরাপদ",
            twoFactor: "টু-ফ্যাক্টর অথেন্টিকেশন",
            enabled: "সক্রিয়",
            manage: "পরিচালনা করুন",
            signOut: "সাইন আউট করুন",
            welcomeMessage: "হ্যালো! আমি AISA, আপনার কৃত্রিম বুদ্ধিমত্তা সুপার অ্যাসিস্ট্যান্ট। আজ আমি আপনাকে কীভাবে সাহায্য করতে পারি?",
            switchedTo: "পরিবর্তন করা হয়েছে",
            heroTitle: "কথোপকথনমূলক এআই-এর উজ্জ্বল ভবিষ্যৎ",
            heroSubtitle: "পরবর্তী প্রজন্মের বুদ্ধিমান সহায়তার অভিজ্ঞতা নিন। AISA ™ একটি অত্যাশ্চর্য ইন্টারফেসের মাধ্যমে রিয়েল-টাইমে আপনার সাথে শেখে, মানিয়ে নেয় এবং তৈরি করে।",
            startNow: "এখনই শুরু করুন",
            privacyTitle: "গোপনীয়তা আগে",
            privacyDesc: "আপনার তথ্য আপনারই। সমস্ত কথোপকথনের জন্য এন্ড-টু-এন্ড এনক্রিপশন।",
            intelligenceTitle: "পরবর্তী প্রজন্মের বুদ্ধিমত্তা",
            intelligenceDesc: "মানুষের মতো যুক্তির জন্য অত্যন্ত উন্নত নিউরাল নেটওয়ার্ক দ্বারা চালিত।",
            interactionTitle: "স্বাভাবিক মিথস্ক্রিয়া",
            interactionDesc: "ভয়েস, টেক্সট বা ফাইল - আপনার কাছে যা সবচেয়ে স্বাভাবিক মনে হয় সেভাবে যোগাযোগ করুন।",
            support: "সহায়তা",
            contact: "যোগাযোগ",
            city: "জবলপুর, মধ্যপ্রদেশ",
            allRightsReserved: "সমস্ত অধিকার সংরক্ষিত।",
            privacyPolicy: "গোপনীয়তা নীতি",
            termsOfService: "পরিষেবার শর্তাবলী",
            cookiePolicy: "কুকি নীতি",
            helpCenter: "সহায়তা কেন্দ্র",
            aboutAisa: "AISA সম্পর্কে",
            apiConnectionError: "দুঃখিত, এই মুহূর্তে AISA নেটওয়ার্কের সাথে সংযোগ করতে সমস্যা হচ্ছে। আপনার ইন্টারনেট সংযোগ পরীক্ষা করুন।",
            apiQuotaExceeded: "AISA সিস্টেম বর্তমানে ব্যস্ত (কোটা সীমা অতিক্রম করেছে)। অনুগ্রহ করে ৬০ সেকেন্ড অপেক্ষা করুন এবং আবার চেষ্টা করুন।",
            faq: "সাধারণ জিজ্ঞাসা",
            help: "সাহায্য",
            existingUser: "বিদ্যমান ব্যবহারকারী",
            sendToSupport: "সাপোর্টে পাঠান",
            ticketSuccess: "টিকিট সফলভাবে জমা দেওয়া হয়েছে! আমাদের টিম শীঘ্রই আপনার সাথে যোগাযোগ করবে।",
            ticketError: "টিকিট জমা দিতে ব্যর্থ হয়েছে। অনুগ্রহ করে আবার চেষ্টা করুন বা সরাসরি আমাদের ইমেল করুন।",
            orEmailUs: "অথবা সরাসরি আমাদের ইমেল করুন",
            faqSubtext: "আমাদের প্ল্যাটফর্ম সম্পর্কে সাধারণ প্রশ্নের দ্রুত উত্তর পান",
            close: "বন্ধ করুন"
        },
        "Marathi": {
            displayLanguage: "प्रदर्शित भाषा",
            dashboard: "डॅशबोर्ड",
            chat: "चॅट",
            myAgents: "माझे एजंट",
            marketplace: "मार्केटप्लेस",
            vendorDashboard: "विक्रेता डॅशबोर्ड",
            billing: "बिलिंग",
            adminDashboard: "प्रशासक डॅशबोर्ड",
            updates: "अपडेट्स",
            helpFaq: "मदत आणि FAQ",
            logOut: "लॉग आउट",
            joined: "डिसेंबर २०२५ मध्ये सामील झाले",
            securityBtn: "सुरक्षा आणि मार्गदर्शक तत्वे",
            totalSessions: "एकूण सत्रे",
            proFeatures: "प्रो वैशिष्ट्ये",
            accountSettings: "खाते सेटिंग्ज",
            credits: "क्रेडिट्स",
            accountPreferences: "खाते पसंती",
            timezone: "वेळ क्षेत्र",
            currency: "चलन",
            theme: "थीम",
            securityStatus: "सुरक्षा स्थिती",
            accountSecure: "खाते पूर्णपणे सुरक्षित आहे",
            twoFactor: "द्वि-घटक प्रमाणीकरण",
            enabled: "सक्षम",
            manage: "व्यवस्थापित करा",
            signOut: "साइन आउट करा",
            welcomeMessage: "नमस्कार! मी AISA आहे, तुमचा आर्टिफिशियल इंटेलिजन्स सुपर असिस्टंट. मी आज तुम्हाला कशी मदत करू शकतो?",
            switchedTo: "वर स्विच केले",
            heroTitle: "संवादात्मक एआयचे भविष्य",
            heroSubtitle: "पुढील पिढीच्या बुद्धिमान समर्थनाचा अनुभव घ्या. AISA ™ एका जबरदस्त इंटरफेसद्वारे रिअल-टाइममध्ये तुमच्यासोबत शिकते, जुळवून घेते आणि तयार करते.",
            startNow: "आता सुरू करा",
            privacyTitle: "गोपनीयता प्रथम",
            privacyDesc: "तुमचा डेटा तुमचा आहे. सर्व संवादांसाठी एंड-टू-एंड एन्क्रिप्शन.",
            intelligenceTitle: "पुढील पिढीची बुद्धिमत्ता",
            intelligenceDesc: "मानवासारख्या तर्कासाठी सर्वात प्रगत न्यूरल नेटवर्क्सद्वारे समर्थित.",
            interactionTitle: "नैसर्गिक संवाद",
            interactionDesc: "आवाज, मजकूर किंवा फायली - तुम्हाला सर्वात नैसर्गिक वाटेल अशा प्रकारे संवाद साधा.",
            support: "समर्थन",
            contact: "संपर्क",
            city: "जबलपूर, मध्य प्रदेश",
            allRightsReserved: "सर्व हक्क राखीव.",
            privacyPolicy: "गोपनीयता धोरण",
            termsOfService: "सेवा अटी",
            cookiePolicy: "कुकी धोरण",
            helpCenter: "मदत केंद्र",
            aboutAisa: "AISA बद्दल",
            apiConnectionError: "क्षमस्व, मला सध्या AISA नेटवर्कशी कनेक्ट करण्यात समस्या येत आहे. कृपया तुमचे कनेक्शन तपासा.",
            apiQuotaExceeded: "AISA सिस्टम सध्या व्यस्त आहे (कोटा मर्यादा संपली आहे). कृपया ६० सेकंद प्रतीक्षा करा आणि पुन्हा प्रयत्न करा.",
            faq: "वारंवार विचारले जाणारे प्रश्न",
            help: "मदत",
            existingUser: "विद्यमान वापरकर्ता",
            sendToSupport: "सपोर्टला पाठवा",
            ticketSuccess: "तिकीट यशस्वीरित्या सबमिट झाले! आमची टीम तुमच्याशी लवकरच संपर्क साधेल.",
            ticketError: "तिकीट सबमिट करण्यात अयशस्वी. कृपया पुन्हा प्रयत्न करा किंवा आम्हाला थेट ईमेल करा.",
            orEmailUs: "किंवा आम्हाला थेट येथे ईमेल करा",
            faqSubtext: "आमच्या प्लॅटफॉर्मबद्दलच्या सामान्य प्रश्नांची त्वरित उत्तरे मिळवा",
            close: "बंद करा"
        },
        "Telugu": {
            displayLanguage: "ప్రదర్శన భాష",
            dashboard: "డాష్‌బోర్డ్",
            chat: "చాట్",
            myAgents: "నా ఏజెంట్లు",
            marketplace: "मार्केटप्लेस",
            vendorDashboard: "విక్రేత డాష్‌బోర్డ్",
            billing: "బిల్లింగ్",
            adminDashboard: "అడ్మిన్ డాష్‌బోర్డ్",
            updates: "నవీకరణలు",
            helpFaq: "సహాయం & ప్రశ్నలు",
            logOut: "లాగ్ అవుట్",
            joined: "డిసెంబర్ 2025లో చేరారు",
            securityBtn: "భద్రత & మార్గదర్శకాలు",
            totalSessions: "మొత్తం సెషన్లు",
            proFeatures: "ప్రో ఫీచర్లు",
            accountSettings: "ఖాతా సెట్టింగ్‌లు",
            credits: "క్రెడిట్స్",
            accountPreferences: "ఖాతా ప్రాధాన్యతలు",
            timezone: "సమయ క్షేత్రం",
            currency: "కరెన్సీ",
            theme: "థీమ్",
            securityStatus: "భద్రతా స్థితి",
            accountSecure: "ఖాతా పూర్తిగా సురక్షితం",
            twoFactor: "రెండు-కారకాల ప్రమాణీకరణ",
            enabled: "ప్రారంభించబడింది",
            manage: "నిర్వహించండి",
            signOut: "సైన్ అవుట్ చేయండి",
            welcomeMessage: "నమస్కారం! నేను AISA, మీ ఆర్టిఫిషియల్ ఇంటెలిజెన్స్ సూపర్ అసిస్టెంట్‌ని. ఈ రోజు నేను మీకు ఎలా సహాయం చేయగలను?",
            switchedTo: "కు మార్చబడింది",
            heroTitle: "సంభాషణ AI యొక్క భవిష్యత్తు",
            heroSubtitle: "తదుపరి తరం తెలివైన మద్దతును అనుభవించండి. AISA ™ అద్భుతమైన ఇంటర్‌ఫేస్ ద్వారా నిజ సమయంలో మీతో నేర్చుకుంటుంది, సర్దుబాటు చేస్తుంది మరియు సృష్టిస్తుంది.",
            startNow: "ఇప్పుడే ప్రారంభించండి",
            privacyTitle: "ముందుగా గోప్యత",
            privacyDesc: "మీ డేటా మీదే. అన్ని సంభాషణల కోసం ఎండ్-టు-ఎండ్ ఎన్‌క్రిప్షన్.",
            intelligenceTitle: "తదుపరి తరం మేధస్సు",
            intelligenceDesc: "మానవ తరహా తర్కం కోసం అత్యంత అధునాతన న్యూరల్ నెట్‌వర్క్‌ల ద్వారా ఆధారితం.",
            interactionTitle: "సహజమైన పరస్పర చర్య",
            interactionDesc: "వాయిస్, టెక్స్ట్ లేదా ఫైల్‌లు - మీకు అత్యంత సహజంగా అనిపించే రీతిలో ఇంటరాక్ట్ అవ్వండి.",
            support: "మద్దతు",
            contact: "సంప్రదించండి",
            city: "జబల్‌పూర్, మధ్యప్రదేశ్",
            allRightsReserved: "అన్ని హక్కులు ప్రత్యేకించబడ్డాయి.",
            privacyPolicy: "గోప్యతా విధానం",
            termsOfService: "సేవా నిబంధనలు",
            cookiePolicy: "కుకీ విధానం",
            helpCenter: "సహాయ కేంద్రం",
            aboutAisa: "AISA గురించి",
            apiConnectionError: "క్షమించండి, ప్రస్తుతం నాకు AISA నెట్‌వర్క్‌కి కనెక్ట్ చేయడంలో సమస్య ఉంది. దయచేసి మీ కనెక్షన్‌ని తనిఖీ చేయండి.",
            apiQuotaExceeded: "AISA సిస్టమ్ ప్రస్తుతం బిజీగా ఉంది (కోటా పరిమితి ముగిసింది). దయచేసి 60 సెకన్లు వేచి ఉండి, మళ్లీ ప్రయత్నించండి.",
            faq: "తరచుగా అడిగే ప్రశ్నలు",
            help: "సహాయం",
            existingUser: "ప్రస్తుత వినియోగదారు",
            sendToSupport: "సపోర్ట్‌కి పంపండి",
            ticketSuccess: "టికెట్ విజయవంతంగా సమర్పించబడింది! మా బృందం త్వరలో మిమ్మల్ని సంప్రదిస్తుంది.",
            ticketError: "టికెట్ సమర్పణ విఫలమైంది. దయచేసి మళ్లీ ప్రయత్నించండి లేదా మాకు నేరుగా ఇమెయిల్ చేయండి.",
            orEmailUs: "లేదా నేరుగా మాకు ఇమెయిల్ చేయండి",
            faqSubtext: "మా ప్లాట్‌ఫారమ్ గురించి సాధారణ ప్రశ్నలకు శీఘ్ర సమాధానాలను పొందండి",
            close: "మూసివేయి"
        },
        "Turkish": {
            displayLanguage: "Görüntüleme Dili",
            dashboard: "Kontrol Paneli",
            chat: "Sohbet",
            myAgents: "Ajanlarım",
            marketplace: "Pazar Yeri",
            vendorDashboard: "Satıcı Paneli",
            billing: "Faturalandırma",
            adminDashboard: "Yönetici Paneli",
            updates: "Güncellemeler",
            helpFaq: "Yardım ve SSS",
            logOut: "Çıkış Yap",
            joined: "Aralık 2025'te katıldı",
            securityBtn: "Güvenlik ve Yönergeler",
            totalSessions: "Toplam Oturumlar",
            proFeatures: "Pro Özellikler",
            accountSettings: "Hesap Ayarları",
            credits: "Krediler",
            accountPreferences: "Hesap Tercihleri",
            timezone: "Saat Dilimi",
            currency: "Para Birimi",
            theme: "Tema",
            securityStatus: "Güvenlik Durumu",
            accountSecure: "Hesap tamamen güvenli",
            twoFactor: "İki Faktörlü Kimlik Doğrulama",
            enabled: "Etkin",
            manage: "Yönet",
            signOut: "Çıkış Yap",
            welcomeMessage: "Merhaba! Ben AISA, Yapay Zeka Süper Asistanınız. Bugün size nasıl yardımcı olabilirim?",
            switchedTo: "Şuna geçildi:",
            heroTitle: "Diyalog tabanlı yapay zekanın geleceği",
            heroSubtitle: "Yeni nesil akıllı desteği deneyimleyin. AISA™, büyüleyici bir arayüz aracılığıyla sizinle birlikte gerçek zamanlı olarak öğrenir, uyum sağlar ve yaratır.",
            startNow: "Şimdi Başla",
            privacyTitle: "Önce Gizlilik",
            privacyDesc: "Verileriniz size aittir. Tüm görüşmeler için uçtan uca şifreleme.",
            intelligenceTitle: "Yeni Nesil Zeka",
            intelligenceDesc: "İnsan benzeri akıl yürütme için en gelişmiş sinir ağları tarafından desteklenmektedir.",
            interactionTitle: "Doğal Etkileşim",
            interactionDesc: "Ses, metin veya dosyalar - size en doğal gelen şekilde etkileşim kurun.",
            support: "Destek",
            contact: "İletişim",
            city: "Jabalpur, Madhya Pradesh",
            allRightsReserved: "Tüm hakları saklıdır.",
            privacyPolicy: "Gizlilik Politikası",
            termsOfService: "Hizmet Şartları",
            cookiePolicy: "Çerez Politikası",
            helpCenter: "Yardım Merkezi",
            aboutAisa: "AISA Hakkında",
            apiConnectionError: "Üzgünüm, şu anda AISA ağına bağlanırken sorun yaşıyorum. Lütfen bağlantınızı kontrol edin.",
            apiQuotaExceeded: "AISA sistemi şu anda meşgul (kota sınırına ulaşıldı). Lütfen 60 saniye bekleyin ve tekrar deneyin.",
            faq: "SSS",
            help: "Yardım",
            existingUser: "Mevcut Kullanıcı",
            sendToSupport: "Desteğe Gönder",
            ticketSuccess: "Bilet başarıyla gönderildi! Ekibimiz yakında sizinle iletiش kuracak.",
            ticketError: "Bilet gönderilemedi. Lütfen tekrar deneyin veya doğrudan bize e-posta gönderin.",
            orEmailUs: "Veya doğrudan bize e-mail gönderin:",
            faqSubtext: "Platformumuz hakkındaki yaygın soruların hızlı yanıtlarını alın",
            close: "Kapat"
        },
        "Tamil": {
            displayLanguage: "காட்சி மொழி",
            dashboard: "முகப்பு",
            chat: "அரட்டை",
            myAgents: "என் முகவர்கள்",
            marketplace: "சந்தை",
            vendorDashboard: "விற்பனையாளர் முகப்பு",
            billing: "பில்லிங்",
            adminDashboard: "நிர்வாக முகப்பு",
            updates: "புதுப்பிப்புகள்",
            helpFaq: "உதவி & கேள்விகள்",
            logOut: "வெளியேறு",
            joined: "டிசம்பர் 2025 இல் இணைந்தார்",
            securityBtn: "பாதுகாப்பு & வழிகாட்டுதல்கள்",
            totalSessions: "மொத்த அமர்வுகள்",
            proFeatures: "ப்ரோ அம்சங்கள்",
            accountSettings: "கணக்கு அமைப்புகள்",
            credits: "க्रेडिटஸ்",
            accountPreferences: "கணக்கு விருப்பங்கள்",
            timezone: "நேர மண்டலம்",
            currency: "நாணயம்",
            theme: "தீம்",
            securityStatus: "பாதுகாப்பு நிலை",
            accountSecure: "கணக்கு முழுமையாக பாதுகாப்பானது",
            twoFactor: "இரண்டு காரணி அங்கீகாரம்",
            enabled: "இயக்கப்பட்டது",
            manage: "நிர்வகி",
            signOut: "வெளியேறு",
            welcomeMessage: "வணக்கம்! நான் AISA, உங்கள் செயற்கை நுண்ணறிவு சூப்பர் அசிஸ்டண்ட். இன்று நான் உங்களுக்கு எப்படி உதவ முடியும்?",
            switchedTo: "மாற்றப்பட்டது",
            heroTitle: "உரையாடல் AI-ன் எதிர்காலம்",
            heroSubtitle: "அடுத்த தலைமுறை அறிவார்ந்த ஆதரவை அனுபவிக்கவும். AISA ™ ஒரு அற்புதமான இடைமுகத்தின் மூலம் உங்களுடன் நிகழ்நேரத்தில் கற்றுக்கொள்கிறது, மாற்றியமைக்கிறது மற்றும் உருவாக்குகிறது.",
            startNow: "இப்போது தொடங்கவும்",
            privacyTitle: "தனியுரிமை முதலில்",
            privacyDesc: "உங்கள் தரவு உங்களுடையது. அனைத்து உரையாடல்களுக்கும் எண்ட்-டு-எண்ட் என்க்ரிப்ஷன்.",
            intelligenceTitle: "அடுத்த தலைமுறை நுண்ணறிவு",
            intelligenceDesc: "மனிதனைப் போன்ற பகுத்தறிவிற்காக மிகவும் மேம்பட்ட நரம்பியல் நெட்வொர்க்குகளால் இயக்கப்படுகிறது.",
            interactionTitle: "இயற்கையான தொடர்பு",
            interactionDesc: "குரல், உரை அல்லது கோப்புகள் - உங்களுக்கு மிகவும் இயல்பாகத் தோன்றும் வகையில் தொடர்பு கொள்ளுங்கள்.",
            support: "ஆதரவு",
            contact: "தொடர்பு",
            city: "ஜபல்பூர், மத்திய பிரதேசம்",
            allRightsReserved: "அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.",
            privacyPolicy: "தனியுரிமைக் கொள்கை",
            termsOfService: "சேவை விதிமுறைகள்",
            cookiePolicy: "குக்கீ கொள்கை",
            helpCenter: "உதவி மையம்",
            aboutAisa: "AISA பற்றி",
            apiConnectionError: "மன்னிக்கவும், தற்போது AISA நெட்வொர்க்குடன் இணைப்பதில் எனக்கு சிக்கல் உள்ளது. உங்கள் இணைப்பைச் சரிபார்க்கவும்.",
            apiQuotaExceeded: "AISA சிஸ்டம் தற்போது வேலையில் உள்ளது (ஒதுக்கீடு வரம்பு எட்டப்பட்டது). தயவுசெய்து 60 வினாடிகள் காத்திருந்து மீண்டும் முயற்சிக்கவும்.",
            faq: "அடிக்கடி கேட்கப்படும் கேள்விகள்",
            help: "உதவி",
            existingUser: "தற்போதுள்ள பயனர்",
            sendToSupport: "ஆதரவுக்கு அனுப்பவும்",
            ticketSuccess: "டிக்கெட் வெற்றிகரமாக சமர்ப்பிக்கப்பட்டது! எங்கள் குழு விரைவில் உங்களைத் தொடர்பு கொள்ளும்.",
            ticketError: "டிக்கெட்டைச் சமர்ப்பிப்பதில் தோல்வி. மீண்டும் முயற்சிக்கவும் அல்லது எங்களுக்கு நேரடியாக மின்னஞ்சல் செய்யவும்.",
            orEmailUs: "அல்லது நேரடியாக எங்களுக்கு மின்னஞ்சல் செய்யவும்",
            faqSubtext: "எங்கள் பிளாட்ஃபார்ம் பற்றிய பொதுவான கேள்விகளுக்கு விரைவான பதில்களைப் பெறுங்கள்",
            close: "மூடு"
        },
        "Kannada": {
            displayLanguage: "ಪ್ರದರ್ಶನ ಭಾಷೆ",
            dashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
            chat: "ಚಾಟ್",
            myAgents: "ನನ್ನ ಏಜೆಂಟ್‌ಗಳು",
            marketplace: "ಮಾರುಕಟ್ಟೆ",
            vendorDashboard: "ಮಾರಾಟಗಾರರ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
            billing: "ಬಿಲ್ಲಿಂಗ್",
            adminDashboard: "ಅಡ್ಮಿನ್ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
            updates: "ನವೀಕರಣಗಳು",
            helpFaq: "ಸಹಾಯ ಮತ್ತು FAQ",
            logOut: "ಲಾಗ್ ಔಟ್",
            joined: "ಡಿಸೆಂಬರ್ 2025 ರಂದು ಸೇರಿದ್ದಾರೆ",
            securityBtn: "ಭದ್ರತೆ ಮತ್ತು ಮಾರ್ಗಸೂಚಿಗಳು",
            totalSessions: "ಒಟ್ಟು ಸೆಷನ್‌ಗಳು",
            proFeatures: "ಪ್ರೊ ವೈಶಿಷ್ಟ್ಯಗಳು",
            accountSettings: "ಖಾತೆ ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
            credits: "ಕ್ರೆಡಿಟ್ಸ್",
            accountPreferences: "ಖಾತೆ ಆದ್ಯತೆಗಳು",
            timezone: "ಸಮಯ ವಲಯ",
            currency: "ಕರೆನ್ಸಿ",
            theme: "ಥೀಮ್",
            securityStatus: "ಭದ್ರತಾ ಸ್ಥಿತಿ",
            accountSecure: "ಖಾತೆ ಸಂಪೂರ್ಣವಾಗಿ ಸುರಕ್ಷಿತವಾಗಿದೆ",
            twoFactor: "ದ್ವಿ-ಅಂಶ ದೃಢೀಕರಣ",
            enabled: "ಸಕ್ರಿಯಗೊಳಿಸಲಾಗಿದೆ",
            manage: "ನಿರ್ವಹಿಸಿ",
            signOut: "ಸೈನ್ ಔಟ್",
            welcomeMessage: "ನಮಸ್ಕಾರ! ನಾನು AISA, ನಿಮ್ಮ ಕೃತಕ ಬುದ್ಧಿಮತ್ತೆ ಸೂಪರ್ ಅಸಿಸ್ಟೆಂಟ್. ಇಂದು ನಾನು ನಿಮಗೆ ಹೇಗೆ ಸಹಾಯ ಮಾಡಲಿ?",
            switchedTo: "ಗೆ ಬದಲಾಯಿಸಲಾಗಿದೆ",
            heroTitle: "ಸಂಭಾಷಣಾತ್ಮಕ AI ನ ಭವಿಷ್ಯ",
            heroSubtitle: "ಮುಂದಿನ ಪೀಳಿಗೆಯ ಬುದ್ಧಿವಂತ ಬೆಂಬಲವನ್ನು ಅನುಭವಿಸಿ. AISA ™ ಅದ್ಭುತ ಇಂಟರ್ಫೇಸ್ ಮೂಲಕ ನೈಜ ಸಮಯದಲ್ಲಿ ನಿಮ್ಮೊಂದಿಗೆ ಕಲಿಯುತ್ತದೆ, ಹೊಂದಿಕೊಳ್ಳುತ್ತದೆ ಮತ್ತು ರಚಿಸುತ್ತದೆ.",
            startNow: "ಈಗಲೇ ಪ್ರಾರಂಭಿಸಿ",
            privacyTitle: "ಗೌಪ್ಯತೆ ಮೊದಲು",
            privacyDesc: "ನಿಮ್ಮ ಡೇಟಾ ನಿಮ್ಮದಾಗಿದೆ. ಎಲ್ಲಾ ಸಂಭಾಷಣೆಗಳಿಗೆ ಎಂಡ್-ಟು-ಎಂಡ್ ಎನ್‌ಕ್ರಿಪ್ಶನ್.",
            intelligenceTitle: "ಮುಂದಿನ ಪೀಳಿಗೆಯ ಬುದ್ಧಿವಂತಿಕೆ",
            intelligenceDesc: "ಮಾನವ ಮಾದರಿಯ ತರ್ಕಕ್ಕಾಗಿ ಅತ್ಯಂತ ಮುಂದುವರಿದ ನ್ಯೂರಲ್ ನೆಟ್‌ವರ್ಕ್‌ಗಳಿಂದ ಚಾಲಿತವಾಗಿದೆ.",
            interactionTitle: "ನೈಸರ್ಗಿಕ ಸಂವಹನ",
            interactionDesc: "ಧ್ವನಿ, ಪಠ್ಯ ಅಥವಾ ಫೈಲ್‌ಗಳು - ನಿಮಗೆ ಹೆಚ್ಚು ನೈಸರ್ಗಿಕವೆಂದು ತೋರುವ ರೀತಿಯಲ್ಲಿ ಸಂವಹನ ನಡೆಸಿ.",
            support: "ಬೆಂಬಲ",
            contact: "ಸಂಪರ್ಕ",
            city: "ಜಬಲ್‌ಪುರ, ಮಧ್ಯಪ್ರದೇಶ",
            allRightsReserved: "ಎಲ್ಲಾ ಹಕ್ಕುಗಳನ್ನು ಕಾಯ್ದಿರಿಸಲಾಗಿದೆ.",
            privacyPolicy: "ಗೌಪ್ಯತಾ ನೀತಿ",
            termsOfService: "ಸೇವಾ ನಿಯಮಗಳು",
            cookiePolicy: "ಕುಕೀ ನೀತಿ",
            helpCenter: "ಸಹಾಯ ಕೇಂದ್ರ",
            aboutAisa: "AISA ಬಗ್ಗೆ",
            apiConnectionError: "ಕ್ಷಮಿಸಿ, ಸದ್ಯಕ್ಕೆ ನನಗೆ AISA ನೆಟ್‌ವರ್ಕ್‌ಗೆ ಸಂಪರ್ಕಿಸಲು ತೊಂದರೆಯಾಗುತ್ತಿದೆ. ದಯವಿಟ್ಟು ನಿಮ್ಮ ಸಂಪರ್ಕವನ್ನು ಪರಿಶೀಲಿಸಿ.",
            apiQuotaExceeded: "AISA ಸಿಸ್ಟಮ್ ಪ್ರಸ್ತುತ ಕಾರ್ಯನಿರತವಾಗಿದೆ (ಕೋಟಾ ಮಿತಿ ತಲುಪಿದೆ). ದಯವಿಟ್ಟು 60 ಸೆಕೆಂಡ್‌ಗಳ ಕಾಲ ಕಾಯಿರಿ ಮತ್ತು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
            faq: "ಪದೇ ಪದೇ ಕೇಳಲಾಗುವ ಪ್ರಶ್ನೆಗಳು",
            help: "ಸಹಾಯ",
            existingUser: "ಅಸ್ತಿತ್ವದಲ್ಲಿರುವ ಬಳಕೆದಾರ",
            sendToSupport: "ಸಪೋರ್ಟ್‌ಗೆ ಕಳುಹಿಸಿ",
            ticketSuccess: "ಟಿಕೆಟ್ ಯಶಸ್ವಿಯಾಗಿ ಸಲ್ಲಿಕೆಯಾಗಿದೆ! ನಮ್ಮ ತಂಡವು ಶೀಘ್ರದಲ್ಲೇ ನಿಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸುತ್ತದೆ.",
            ticketError: "ಟಿಕೆಟ್ ಸಲ್ಲಿಸಲು ವಿಫಲವಾಗಿದೆ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ ಅಥವಾ ನಮಗೆ ನೇರವಾಗಿ ಇಮೇಲ್ ಮಾಡಿ.",
            orEmailUs: "ಅಥವಾ ನೇರವಾಗಿ ನಮಗೆ ಇಲ್ಲಿ ಇಮೇಲ್ ಮಾಡಿ",
            faqSubtext: "ನಮ್ಮ ಪ್ಲಾಟ್‌ಫಾರ್ಮ್ ಕುರಿತು ಸಾಮಾನ್ಯ ಪ್ರಶ್ನೆಗಳಿಗೆ ತ್ವರಿತ ಉತ್ತರಗಳನ್ನು ಪಡೆಯಿರಿ",
            close: "ಮುಚ್ಚಿ"
        },
        "Malayalam": {
            displayLanguage: "പ്രദർശന ഭാഷ",
            dashboard: "ഡാഷ്‌ബോർഡ്",
            chat: "ചാറ്റ്",
            myAgents: "എന്റെ ഏജന്റുകൾ",
            marketplace: "മാർക്കറ്റ് പ്ലേസ്",
            vendorDashboard: "വെണ്ടർ ഡാഷ്‌ബോർഡ്",
            billing: "ബില്ലിംഗ്",
            adminDashboard: "അഡ്മിൻ ഡാഷ്‌ബോർഡ്",
            updates: "അപ്‌ഡേറ്റുകൾ",
            helpFaq: "സഹായം & FAQ",
            logOut: "ലോഗ് ഔട്ട്",
            joined: "2025 ഡിസംബറിൽ ചേർന്നു",
            securityBtn: "സുരക്ഷയും മാർഗ്ഗനിർദ്ദേശങ്ങളും",
            totalSessions: "ആകെ സെഷനുകൾ",
            proFeatures: "പ്രോ ഫീച്ചറുകൾ",
            accountSettings: "അക്കൗണ്ട് ക്രമീകരണങ്ങൾ",
            credits: "ക്രെഡിറ്റുകൾ",
            accountPreferences: "അക്കൗണ്ട് മുൻഗണനകൾ",
            timezone: "സമയ മേഖല",
            currency: "കറൻസി",
            theme: "തീം",
            securityStatus: "സുരക്ഷാ നില",
            accountSecure: "അക്കൗണ്ട് പൂർണ്ണമായും സുരക്ഷിതമാണ്",
            twoFactor: "ടു-ഫാക്ടർ ഓതന്റിക്കേഷൻ",
            enabled: "പ്രവർത്തനക്ഷമമാക്കി",
            manage: "നിയന്ത്രിക്കുക",
            signOut: "സൈൻ ഔട്ട്",
            welcomeMessage: "നമസ്കാരം! ഞാൻ AISA ആണ്, നിങ്ങളുടെ ആർട്ടിഫിഷ്യൽ ഇന്റലിജൻസ് സൂപ്പർ അസിസ്റ്റന്റ്. ഇന്ന് എനിക്ക് നിങ്ങളെ എങ്ങനെ സഹായിക്കാൻ കഴിയും?",
            switchedTo: "ലേക്ക് മാറ്റി",
            heroTitle: "സംഭാഷണ എഐയുടെ ഭാവി",
            heroSubtitle: "അടുത്ത തലമുറയിലെ ബുദ്ധിപരമായ പിന്തുണ അനുഭവിച്ചറിയൂ. AISA ™ ഒരു മനോഹരമായ ഇന്റർഫേസിലൂടെ തത്സമയം നിങ്ങളോടൊപ്പം പഠിക്കുകയും പൊരുത്തപ്പെടുകയും സൃഷ്ടിക്കുകയും ചെയ്യുന്നു.",
            startNow: "ഇപ്പോൾ ആരംഭിക്കുക",
            privacyTitle: "സ്വകാര്യതയ്ക്ക് പ്രഥമ പരിഗണന",
            privacyDesc: "നിങ്ങളുടെ ഡാറ്റ നിയന്ത്രിക്കുന്നത് നിങ്ങളാണ്. എല്ലാ സംഭാഷണങ്ങൾക്കും എൻഡ്-ടു-എൻഡ് എൻക്രിപ്ഷൻ.",
            intelligenceTitle: "അടുത്ത തലമുറ ഇന്റലിജൻസ്",
            intelligenceDesc: "മനുഷ്യതുല്യമായ യുക്തിചിന്തയ്ക്കായി ഏറ്റവും നൂതനമായ ന്യൂറൽ നെറ്റ്‌വർക്കുകളാൽ പ്രവർത്തിക്കുന്നു.",
            interactionTitle: "സ്വാഭാവിക ഇടപെടൽ",
            interactionDesc: "ശബ്ദം, വാചകം അല്ലെങ്കിൽ ഫയലുകൾ - നിങ്ങൾക്ക് ഏറ്റവും സ്വാഭാവികമായി തോന്നുന്ന രീതിയിൽ ഇടപഴകുക.",
            support: "പിന്തുണ",
            contact: "ബന്ധപ്പെടുക",
            city: "ജബൽപൂർ, മധ്യപ്രദേശ്",
            allRightsReserved: "എല്ലാ അവകാശങ്ങളും നിക്ഷിപ്തം.",
            privacyPolicy: "സ്വകാര്യതാ നയം",
            termsOfService: "സേവന നിബന്ധനകൾ",
            cookiePolicy: "കുക്കി നയം",
            helpCenter: "സഹായ കേന്ദ്രം",
            aboutAisa: "AISA-യെ കുറിച്ച്",
            apiConnectionError: "ക്ഷമിക്കണം, എനിക്ക് ഇപ്പോൾ AISA നെറ്റ്‌വർക്കുമായി ബന്ധിപ്പിക്കാൻ കഴിയുന്നില്ല. ദയവായി നിങ്ങളുടെ കണക്ഷൻ പരിശോധിക്കുക.",
            apiQuotaExceeded: "AISA സിസ്റ്റം ഇപ്പോൾ തിരക്കിലാണ് (ക്വാട്ട പരിധി കവിഞ്ഞു). ദയവായി 60 സെക്കൻഡ് കാത്തിരുന്ന ശേഷം വീണ്ടും ശ്രമിക്കുക.",
            faq: "പതിവ് ചോദ്യങ്ങൾ",
            help: "സഹായം",
            existingUser: "നിലവിലുള്ള ഉപയോക്താവ്",
            sendToSupport: "സപ്പോർട്ടിലേക്ക് അയക്കുക",
            ticketSuccess: "ടിക്കറ്റ് വിജയകരമായി സമർപ്പിച്ചു! ഞങ്ങളുടെ ടീം ഉടൻ നിങ്ങളെ ബന്ധപ്പെടും.",
            ticketError: "ടിക്കറ്റ് സമർപ്പിക്കുന്നതിൽ പരാജയപ്പെട്ടു. ദയവായി വീണ്ടും ശ്രമിക്കുക അല്ലെങ്കിൽ ഞങ്ങൾക്ക് നേരിട്ട് ഇമെയിൽ അയയ്ക്കുക.",
            orEmailUs: "അല്ലെങ്കിൽ നേരിട്ട് ഞങ്ങൾക്ക് ഇമെയിൽ അയയ്ക്കുക:",
            faqSubtext: "ഞങ്ങളുടെ പ്ലാറ്റ്‌ഫോമിനെക്കുറിച്ചുള്ള പൊതുവായ ചോദ്യങ്ങൾക്ക് പെട്ടെന്ന് മറുപടി നേടുക",
            close: "അടയ്ക്കുക"
        },
        "Italian": {
            displayLanguage: "Lingua di visualizzazione",
            dashboard: "Dashboard",
            chat: "Chat",
            myAgents: "I miei agenti",
            marketplace: "Mercato",
            vendorDashboard: "Dashboard fornitore",
            billing: "Fatturazione",
            adminDashboard: "Dashboard amministratore",
            updates: "Aggiornamenti",
            helpFaq: "Aiuto e FAQ",
            logOut: "Disconnetti",
            joined: "Iscritto a dicembre 2025",
            securityBtn: "Sicurezza e linee guida",
            totalSessions: "Sessioni totali",
            proFeatures: "Funzionalità Pro",
            accountSettings: "Impostazioni account",
            credits: "Crediti",
            accountPreferences: "Preferenze account",
            timezone: "Fuso orario",
            currency: "Valuta",
            theme: "Tema",
            securityStatus: "Stato di sicurezza",
            accountSecure: "Account completamente sicuro",
            twoFactor: "Autenticazione a due fattori",
            enabled: "Abilitato",
            manage: "Gestisci",
            signOut: "Disconnetti",
            welcomeMessage: "Ciao! Sono AISA, il tuo Super Assistente di Intelligenza Artificiale. Come posso aiutarti oggi?",
            switchedTo: "Passato a",
            heroTitle: "Il futuro dell'IA conversazionale",
            heroSubtitle: "Sperimenta la prossima generazione di supporto intelligente. AISA ™ impara, si adatta e crea con te in tempo reale attraverso un'interfaccia mozzafiato.",
            startNow: "Inizia Ora",
            privacyTitle: "La privacy prima di tutto",
            privacyDesc: "I tuoi dati appartengono a te. Crittografia end-to-end per tutte le conversazioni.",
            intelligenceTitle: "Intelligenza di nuova generazione",
            intelligenceDesc: "Basato sulle reti neurali più avanzate per un ragionamento simile a quello umano.",
            interactionTitle: "Interazione naturale",
            interactionDesc: "Voce, testo o file: interagisci nel modo che ti sembra più naturale.",
            support: "Supporto",
            contact: "Contatto",
            city: "Jabalpur, Madhya Pradesh",
            allRightsReserved: "Tutti i diritti riservati.",
            privacyPolicy: "Informativa sulla privacy",
            termsOfService: "Termini di servizio",
            cookiePolicy: "Informativa sui cookie",
            helpCenter: "Centro assistenza",
            aboutAisa: "Informazioni su AISA",
            apiConnectionError: "Spiacenti, al momento ho problemi a connettermi alla rete AISA. Controlla la tua connessione.",
            apiQuotaExceeded: "Il sistema AISA è attualmente occupato (limite di quota raggiunto). Attendi 60 secondi e riprova.",
            faq: "FAQ",
            help: "Aiuto",
            existingUser: "Utente Esistente",
            sendToSupport: "Invia al supporto",
            ticketSuccess: "Ticket inviato con successo! Il nostro team ti contatterà presto.",
            ticketError: "Impossibile inviare il ticket. Riprova o inviaci un'e-mail direttamente.",
            orEmailUs: "Oppure inviaci un'e-mail direttamente a",
            faqSubtext: "Ottieni risposte rapide alle domande comuni sulla nostra piattaforma",
            close: "Chiudi"
        },
        "Dutch": {
            displayLanguage: "Weergavetaal",
            dashboard: "Dashboard",
            chat: "Chat",
            myAgents: "Mijn agenten",
            marketplace: "Marktplaats",
            vendorDashboard: "Leveranciersdashboard",
            billing: "Facturering",
            adminDashboard: "Beheerdersdashboard",
            updates: "Updates",
            helpFaq: "Hulp & FAQ",
            logOut: "Uitloggen",
            joined: "Lid sinds december 2025",
            securityBtn: "Beveiliging & Richtlijnen",
            totalSessions: "Totaal aantal sessies",
            proFeatures: "Pro-functies",
            accountSettings: "Accountinstellingen",
            credits: "Credits",
            accountPreferences: "Accountvoorkeuren",
            timezone: "Tijdzone",
            currency: "Valuta",
            theme: "Thema",
            securityStatus: "Beveiligingsstatus",
            accountSecure: "Account volledig beveiligd",
            twoFactor: "Tweefactorauthenticatie",
            enabled: "Ingeschakeld",
            manage: "Beheren",
            signOut: "Uitloggen",
            welcomeMessage: "Hallo! Ik ben AISA, jouw Kunstmatige Intelligentie Super Assistent. Hoe kan ik je vandaag helpen?",
            switchedTo: "Opgeschakeld naar",
            heroTitle: "De toekomst van conversatie-AI",
            heroSubtitle: "Ervaar de volgende generatie intelligente ondersteuning. AISA ™ leert, past zich aan en creëert samen met jou in realtime via een verbluffende interface.",
            startNow: "Nu Beginnen",
            privacyTitle: "Privacy Eerst",
            privacyDesc: "Jouw gegevens zijn van jou. End-to-end versleuteling voor alle gesprekken.",
            intelligenceTitle: "Volgende Generatie Intelligentie",
            intelligenceDesc: "Aangestuurd door de meest geavanceerde neurale netwerken voor mensachtig redeneren.",
            interactionTitle: "Natuurlijke Interactie",
            interactionDesc: "Spraak, tekst of bestanden – interacteer op de manier die het meest natuurlijk aanvoelt.",
            support: "Ondersteuning",
            contact: "Contact",
            city: "Jabalpur, Madhya Pradesh",
            allRightsReserved: "Alle rechten voorbehouden.",
            privacyPolicy: "Privacybeleid",
            termsOfService: "Servicevoorwaarden",
            cookiePolicy: "Cookiebeleid",
            helpCenter: "Helpcentrum",
            aboutAisa: "Over AISA",
            apiConnectionError: "Sorry, ik heb momenteel problemen om verbinding te maken met het AISA-netwerk. Controleer je verbinding.",
            apiQuotaExceeded: "Het AISA-systeem is momenteel druk (quotumlimiet bereikt). Wacht 60 seconden en probeer het opnieuw.",
            faq: "FAQ",
            help: "Hulp",
            existingUser: "Bestaande Gebruiker",
            sendToSupport: "Verzenden naar Support",
            ticketSuccess: "Ticket succesvol ingediend! Ons team neemt binnenkort contact met je op.",
            ticketError: "Fout bij het indienen van ticket. Probeer het opnieuw of stuur ons direct een e-mail.",
            orEmailUs: "Of stuur ons direct een e-mail naar",
            faqSubtext: "Krijg snel antwoord op veelgestelde vragen over ons platform",
            close: "Sluiten"
        },
        "Urdu": {
            displayLanguage: "نمایاں زبان",
            dashboard: "ڈیش بورڈ",
            chat: "چیٹ",
            myAgents: "میرے ایجنٹس",
            marketplace: "مارکیٹ پلیس",
            vendorDashboard: "وینڈر ڈیش بورڈ",
            billing: "بلنگ",
            adminDashboard: "ایڈمن ڈیش بورڈ",
            updates: "اپ ڈیٹس",
            helpFaq: "مدد اور سوالات",
            logOut: "لاگ آؤٹ",
            joined: "دسمبر 2025 میں شامل ہوئے",
            securityBtn: "سیکیورٹی اور رہنما اصول",
            totalSessions: "کل سیشنز",
            proFeatures: "پرو خصوصیات",
            accountSettings: "اکاؤنٹ کی ترتیبات",
            credits: "کریڈٹ",
            accountPreferences: "اکاؤنٹ کی ترجیحات",
            timezone: "ٹائم زون",
            currency: "کرنسی",
            theme: "تھیم",
            securityStatus: "سیکیورٹی کی صورتحال",
            accountSecure: "اکاؤنٹ مکمل طور پر محفوظ ہے",
            twoFactor: "دو قدمی تصدیق",
            enabled: "فعال",
            manage: "انتظام کریں",
            signOut: "ساین آؤٹ",
            welcomeMessage: "ہیلو! میں ہوں AISA، آپ کا مصنوعی ذہانت کا سپر اسسٹنٹ۔ میں آج آپ کی کیسے مدد کر سکتا ہوں؟",
            switchedTo: "تبدیل کر دیا گیا",
            heroTitle: "گفتگو پر مبنی اے آئی کا مستقبل",
            heroSubtitle: "ذہین مدد کی اگلی نسل کا تجربہ کریں۔ AISA ™ ایک شاندار انٹرفیس کے ذریعے حقیقی وقت میں آپ کے ساتھ سیکھتا ہے، مطابقت رکھتا ہے اور تخلیق کرتا ہے۔",
            startNow: "ابھی شروع کریں",
            privacyTitle: "رازداری سب سے پہلے",
            privacyDesc: "آپ کا ڈیٹا آپ کا ہے۔ تمام گفتگو کے لیے اینڈ ٹو اینڈ انکرپشن۔",
            intelligenceTitle: "اگلی نسل کی ذہانت",
            intelligenceDesc: "انسانی طرز کی استدلال کے لیے جدید ترین نیورل نیٹ ورکس کے ذریعے تقویت یافتہ۔",
            interactionTitle: "قدرتی تعامل",
            interactionDesc: "آواز، متن یا فائلیں - اس طریقے سے تعامل کریں جو سب سے زیادہ قدرتی محسوس ہو۔",
            support: "سپورٹ",
            contact: "رابطہ کریں",
            city: "جبل پور، مدھیہ پردیش",
            allRightsReserved: "جملہ حقوق محفوظ ہیں۔",
            privacyPolicy: "رازداری کی پالیسی",
            termsOfService: "سروس کی شرائط",
            cookiePolicy: "کوکی پالیسی",
            helpCenter: "ہیلپ سینٹر",
            aboutAisa: "AISA کے بارے میں",
            apiConnectionError: "معذرت، مجھے اس وقت AISA نیٹ ورک سے منسلک ہونے میں دشواری ہو رہی ہے۔ براہ کرم اپنا کنکشن چیک کریں۔",
            apiQuotaExceeded: "AISA سسٹم اس وقت مصروف ہے (کوٹے کی حد ختم ہو گئی ہے)۔ براہ کرم 60 سیکنڈ انتظار کریں اور دوبارہ کوشش کریں۔",
            faq: "اکثر پوچھے گئے سوالات",
            help: "مدد",
            existingUser: "موجودہ صارف",
            sendToSupport: "سپورٹ کو بھیجیں",
            ticketSuccess: "ٹکٹ کامیابی کے ساتھ جمع ہو گیا! ہماری ٹیم جلد آپ سے رابطہ کرے گی۔",
            ticketError: "ٹکٹ جمع کرنے میں ناکامی۔ براہ کرم دوبارہ کوشش کریں یا ہمیں براہ راست ای میل کریں۔",
            orEmailUs: "یا ہمیں براہ راست ای میل کریں",
            faqSubtext: "ہمارے پلیٹ فارم کے بارے میں عام سوالات کے فوری جوابات حاصل کریں",
            close: "بند کریں"
        },
    };

    const t = (key) => {
        const langData = translations[language] || translations['English'];
        return langData[key] || translations['English'][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t, languages: uniqueLanguages, region, setRegion, regions, regionFlags, allTimezones, regionTimezones }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => useContext(LanguageContext);
